# POST http://localhost:5557/createinvoice
# Content-Type: application/json

# GET https://citi.edu.mn/payments?payment_id=1686715984011

# POST http://localhost:5557/createinvoice
# Content-Type: application/json

# {
#     "firstName": "Setsen",
#     "registration": "ХЛ77102910",
#     "middleName": "Batmunkh",
#     "phone1": "99114366",
#     "amount": 12000,
#     "applicantId": "setsenwn@gmail.com"
# }

# POST https://merchant.qpay.mn/v2/auth/token
# Authorization: Basic Q0lUWV9VTklWRVJfRUNPTTo4ams3RTk2YQ==
# Content-Type: application/json

# {
#     "data": "raw"
# }

GET http://localhost:5557/getapplicants

# POST http://localhost:5557/getusertasks
# Content-Type: application/json

# {
#     "username": "setsen.batmunkh@citi.edu.mn"
# }